Merge #1460: netbase: Do not print an error on connection timeouts through proxy
fdca17c3251da125afda75e7673080df1810c9fc Consolidate scattered max peer connection values into single declaration. (furszy)
bd4c7137c7f8925120e6c5e789f6fb8af724528d netbase: Do not print an error on connection timeouts through proxy If a timeout happens while reading the proxy response, this effectively means we timed out while connecting to the remote node. This is very common for Tor, so do not print an error message. (furszy)
f936a2f5e23ef88378102d3aa214ee07b14beb2e netbase: Make InterruptibleRecv return an error code instead of bool. (furszy)

Pull request description:

  If a timeout happens while reading the proxy response, this effectively means we timed out while connecting to the remote node. This is very common for Tor, so do not print an error message to the log in that case.

  Avoids a flood of
  ```
  ERROR: Error reading proxy response
  ```

  while running through Tor, causing users to blame the proxy.

  Coming from upstream [9726](https://github.com/bitcoin/bitcoin/pull/9726)

ACKs for top commit:
  Fuzzbawls:
    utACK fdca17c3251da125afda75e7673080df1810c9fc
  random-zebra:
    utACK fdca17c3251da125afda75e7673080df1810c9fc

Tree-SHA512: 6007c544710a0b103712f134c962368bd4704bbea4e1b93ccc55dd5ce65db063089facf3cdd335b132920256a9fe3fe59ed8e81add57f8ba85e9a7589c086961